<a href="https://colab.research.google.com/github/alviyandriadillah/Machine-Learning/blob/main/KNN_as_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Python Packages**

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**Download Iris Dataset**

In [3]:
path = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

**assign column names to the dataset**

In [4]:
headernames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

**Read dataset to pandas dataframe**

In [5]:
dataset = pd.read_csv(path, names = headernames)
dataset.head()

sepal-length  sepal-width  petal-length  petal-width        Class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

***Data Preprocessing ***

In [6]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

**Train data**

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40)

**Data Scalling**

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

**Train data with KNN**

In [9]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 8)
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=8, p=2,
                     weights='uniform')

**Make Prediction**

In [11]:
y_pred = classifier.predict(X_test)

**Print the Results**

In [12]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[17  0  0]
 [ 0 22  0]
 [ 0  1 20]]
Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        17
Iris-versicolor       0.96      1.00      0.98        22
 Iris-virginica       1.00      0.95      0.98        21

       accuracy                           0.98        60
      macro avg       0.99      0.98      0.98        60
   weighted avg       0.98      0.98      0.98        60

Accuracy: 0.9833333333333333
